disabled_rules: # rule identifiers to exclude from running
  - todo
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
type_name:
  excluded:
    - K
identifier_name:
  excluded: # excluded via string array
    - vc
