#!/usr/bin/ruby

default_platform(:ios)

platform :ios do
  desc "Set up certificates and code signing"
  lane :certificates do
    ["appstore", "development"].each { |type|
      provision(type: type)
    }
  end

  private_lane :provision do |options|
    type = options[:type]
    match(
      git_url: "git@github.com:jasonzurita/ios-certificates.git",
      username: "ios-dev@flippingleaf.com",
      app_identifier: [
        "com.jasonzurita.babypatterns",
        "com.flippingleaf.*",
        "com.jasonzurita.babypatterns.watchkitapp.watchkitextension",
        "com.jasonzurita.babypatterns.watchkitapp",
      ],
      type: type,
      skip_docs: true,
      force_for_new_devices: true,
    )
  end

  desc "Register new device for development"
  lane :register_new_device do
    device_name = prompt(text: "Enter the device name: ")
    device_udid = prompt(text: "Enter the device UDID: ")
    register_devices(
      username: "ios-dev@flippingleaf.com",
      devices: {device_name => device_udid}
    )
    provision(type: "development")
  end

  desc "Build dependencies"
  lane :build_dependencies do
    cocoapods(
      use_bundle_exec: false,
      repo_update: true,
    )
  end

  desc "Run tests"
  lane :test do
    scan(
      scheme: "BabyPatterns",
      clean: true,
      skip_build: true,
      # This needs to match with the CircleCI config yml
      output_directory: "artifacts/tests",
      output_files: "report.html",
      output_types: "html",
      devices: ["iPhone 8"],
      code_coverage: true,
    )
  end
end

